

services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
      - ./proxy/html:/usr/share/nginx/html:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  #  depends_on:
  #    - app

  #app:
  #  build:
  #    context: ./app
  #    dockerfile: Dockerfile
  #  ports:
  #    - "3000:3000"
  #  restart: always
  #  volumes:
  #    - ./app:/app
  #    - /app/node_modules
  #  environment:
  #    - DATABASE_URL=postgres://user:password@db:5432/mydatabase
  #  depends_on:
  #    - db

  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
